fix: minor fixes

diff --git a/.bmeme/bin/app b/.bmeme/bin/app
--- a/.bmeme/bin/app
+++ b/.bmeme/bin/app
@@ -9,4 +9,11 @@ done
 
 if [[ -t 1 ]] ; then OPTS=""; else OPTS="-T"; fi
 
+docker-compose ps app | grep -q Up | true
+ret=${PIPESTATUS[1]}
+if [ $ret -eq 1 ]; then
+  echo "Error - It seems that the app container is not running"
+  exit 1
+fi
+
 docker-compose exec -u $(id -u):$(id -g) ${OPTS} app /bin/bash -c "${PARAMS}"
